### ISSUE TITLE
Create tags/release

### ISSUE THREAD

**Issue by barnumbirr** [pb-/gotypist#13]
Hello,

thanks for creating `gotypist`, I've really been enjoying using it. I'd be interested in creating and maintaining a Debian package for it and I was wondering if you would consider using tags/releases for the project? This would help a lot in packaging as I won't have to build from some "random" commit on `master`.

Cheers.

**Comment by pb-** [comment]
Hey,

glad to hear you're enjoying `gotypist`. I've just tagged the current version as 0.8.0, excited to see a Debian package for it!

**Comment by barnumbirr** [comment]
Hello,

thanks a lot for the tag/release. :tada:
Packages are "live" at [barnumbirr/gotypist-debian](https://github.com/barnumbirr/gotypist-debian/releases). If you're interested in adding them to the `Installation` section of the project's `README`, let me know what formatting you'd like me to follow and I'll draft up a PR.

Cheers.

**Comment by pb-** [comment]
Thanks :confetti_ball:! Feel free to create a PR with installation instructions, no particular format preferred.

**Comment by barnumbirr** [comment]
Here goes nothing. I've subscribed to `gotypist` releases so I'll try and keep the package updated.

Cheers.
