### ISSUE TITLE
Module path should be "github.com/pb-/gotypist", not "github.com/eggman64/gotypist"

### ISSUE THREAD

**Issue by KateGo520** [pb-/gotypist#16]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, as README said, run `go get github.com/pb-/gotypist`:

```
go: downloading github.com/pb-/gotypist v0.0.0-20200518181917-072901ed1503
go: github.com/pb-/gotypist upgrade => v0.0.0-20200518181917-072901ed1503
go get: github.com/pb-/gotypist@v0.0.0-20200518181917-072901ed1503: parsing go.mod:
        module declares its path as: github.com/eggman64/gotypist
                but was required as: github.com/pb-/gotypist 
```

###  Fix the module path:
1）Rename the module path to "go get github.com/pb-/gotypist": https://github.com/pb-/gotypist/blob/master/go.mod#L1 
```
module github.com/pb-/gotypist
go 1.14
require (
	…
) 
```
2） Warning the users not to use the module, get "github.com/pb-/gotypist" in GOPATH mode.

**Comment by KateGo520** [comment]
@barnumbirr  @eggman64  Could you help me review this issue? Thx :p

**Comment by pb-** [comment]
Fixed.
