### ISSUE TITLE
Proposal: Remove word minium or make it configurable.

### ISSUE THREAD

**Issue by adamryman** [pb-/gotypist#5]
```
	if err != nil || len(words) < 9 {
```

I want to pass in text that looks like this:
```
; ??? ; ??? ; ??? ; ??? ; ??? ; ??? ; ??? ; ???
??? ;;; ??? ;;; ??? ;;; ;?; ;?; ;?; ;?; ;?; ;?;
??; ??; ??; ;;? ;;? ;;? ?;? ?;? ?;? ?;? ?;? ?;??
```

To practice typing punctuation. 

Possibly remove this `len(word) < 9` limit?

Could you explain the logic here? I am going to guess it relates to the `/usr/share/dict/words` having one word per line?

Thanks.

**Comment by pb-** [comment]
There's really no deeper reason for this, I relaxed the limit to require at least one word/line :+1:.
