### ISSUE TITLE
Implement flag to pass lines of a file rather than a word file.

### ISSUE THREAD

**Issue by adamryman** [pb-/gotypist#6]
```
-l FILE
  use lines from FILE
```
Allows the user to pass specific lines of text they want to practice, rather than using the words in a random order.

I highly suggest that by default it plays the lines sequentially from top to bottom.

That way a user could save files as `lessons`, and they would be reproducible.

Example, I want to learn `?` and `;`. I use this file.
```
; ??? ; ??? ; ??? ; ??? ; ??? ; ??? ; ??? ; ???
??? ;;; ??? ;;; ??? ;;; ;?; ;?; ;?; ;?; ;?; ;?;
??; ??; ??; ;;? ;;? ;;? ?;? ?;? ?;? ?;? ?;? ?;??
```
 
Possibly another flag
```
-r bool
   randomize line output with -l
```
To get that effect.

I would be happy to put up a PR with this functionality if desired.

**Comment by pb-** [comment]
I like this idea a lot, especially the lessons. With [this commit](https://github.com/pb-/gotypist/commit/f05f30860219fb740089ff52986c5f22d7c7a4b9) adding that kind of functionality should be easier now :tada:.

**Comment by pb-** [comment]
Added in a9d0faa500599dc645a5d1c1667aca09a3e831d6.

**Comment by adamryman** [comment]
Darn! I kept meaning to get to it. Now I gotta think of another sweet feature to add...


Thanks for implementing though!
