### ISSUE TITLE
Broken characters

### ISSUE THREAD

**Issue by kroppt** [pb-/gotypist#8]
Please see the attached image:

![image](https://user-images.githubusercontent.com/14015672/39413229-4fc6c422-4bf5-11e8-8390-2b5223799aab.png)

My terminal emulator is using UTF-8, and I tried Noto Mono, Ubuntu Mono, Monospace, Liberation Mono, Courier New, and Andale Mono... Not sure how to fix this.

**Comment by pb-** [comment]
Thanks for your report, that looks odd. Which terminal emulator (and version) are you running?

**Comment by kroppt** [comment]
GNOME Terminal 3.24.2
Using VTE version 0.48.4 +GNUTLS
`TERM=xterm-256color`
`SHELL=/bin/bash`
`go version go1.10.1 linux/amd64`

**Comment by pb-** [comment]
Unfortunately I don't have these versions readily available to reproduce, could you perhaps verify if the problem is also present in the examples of `go-termbox` in order to rule out any upstream issues? https://github.com/nsf/termbox-go

If these work fine, then I'd try to get the exact versions on my system.

**Comment by kroppt** [comment]
Yes, that works fine. So far, this is the only project that hasn't worked with depends on termbox.

**Comment by pb-** [comment]
I booted a clean Ubuntu 17.10 system which matches these exact versions and configuration, using various fonts - everything works as expected for me. Do you have more non-default terminal-related configuration?

**Comment by kroppt** [comment]
I can't think of anything in particular that might affect this.

I use Gentoo Linux with GNOME on both my laptop and desktop, and it's happening on both. I also tried on go1.9 and go1.10.2 with no luck. Not sure what could be different about our systems to cause this. I don't know very much about desktop environments and terminals and whatnot.

**Comment by eggman64** [comment]
unfortunately this happens for me as well:
go version `go1.11.5 linux/amd64`
kernel `4.20.5-arch1-1-ARCH` 

and the termbox-go examples display fonts with no problem

![2019-02-04_12 36 47](https://user-images.githubusercontent.com/2733735/52206127-9952b900-2879-11e9-953f-df9b913ce742.png)
